[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.0", features = ["derive"] }
rand = "0.8.5"
serde = { version = "1.0.208", features = ["std", "derive", "serde_derive"] }
serde_json = "1.0.125"
srand = "0.4.0"
